

export const styles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#f5f5f0",
    padding: "2rem 1rem",
    fontFamily: "'Georgia', serif",
  },
  card: {
    background: "#ffffff",
    borderRadius: "16px",
    padding: "2.5rem",
    width: "100%",
    maxWidth: "420px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08), 0 8px 32px rgba(0,0,0,0.06)",
  },
  logo: {
    width: "44px",
    height: "44px",
    borderRadius: "10px",
    background: "#1a1a2e",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "1.5rem",
    fontSize: "22px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "600",
    color: "#111",
    marginBottom: "4px",
    letterSpacing: "-0.5px",
  },
  subtitle: {
    fontSize: "14px",
    color: "#888",
    marginBottom: "2rem",
  },
  fieldWrapper: {
    marginBottom: "1rem",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: "500",
    color: "#555",
    marginBottom: "6px",
    fontFamily: "'Arial', sans-serif",
  },
  inputWrap: {
    position: "relative",
  },
  inputIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: "16px",
    color: "#aaa",
    pointerEvents: "none",
    fontFamily: "sans-serif",
  },
  input: {
    width: "100%",
    padding: "10px 12px 10px 38px",
    border: "1px solid #e0e0e0",
    borderRadius: "10px",
    fontSize: "14px",
    color: "#111",
    background: "#fafafa",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "'Arial', sans-serif",
    transition: "border-color 0.15s, box-shadow 0.15s",
  },
  inputFocus: {
    borderColor: "#4f46e5",
    boxShadow: "0 0 0 3px rgba(79,70,229,0.1)",
    background: "#fff",
  },
  togglePw: {
    position: "absolute",
    right: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "15px",
    color: "#aaa",
    padding: "0",
    lineHeight: 1,
  },
  errorText: {
    fontSize: "12px",
    color: "#e53e3e",
    marginTop: "4px",
    fontFamily: "'Arial', sans-serif",
  },
  row: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "7px",
    fontSize: "13px",
    color: "#666",
    cursor: "pointer",
    fontFamily: "'Arial', sans-serif",
  },
  checkbox: {
    width: "15px",
    height: "15px",
    accentColor: "#4f46e5",
    cursor: "pointer",
  },
  forgotLink: {
    fontSize: "13px",
    color: "#4f46e5",
    textDecoration: "none",
    fontFamily: "'Arial', sans-serif",
  },
  btnPrimary: {
    width: "100%",
    padding: "11px",
    background: "#1a1a2e",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: "500",
    cursor: "pointer",
    marginBottom: "1rem",
    fontFamily: "'Arial', sans-serif",
    letterSpacing: "0.2px",
    transition: "opacity 0.15s",
  },
  btnPrimaryDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
  divider: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "1rem",
  },
  dividerLine: {
    flex: 1,
    border: "none",
    borderTop: "1px solid #eee",
  },
  dividerText: {
    fontSize: "12px",
    color: "#aaa",
    whiteSpace: "nowrap",
    fontFamily: "'Arial', sans-serif",
  },
  btnGoogle: {
    width: "100%",
    padding: "10px",
    border: "1px solid #e0e0e0",
    borderRadius: "10px",
    background: "#fff",
    fontSize: "14px",
    color: "#333",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginBottom: "1.75rem",
    fontFamily: "'Arial', sans-serif",
    transition: "background 0.15s",
  },
  signupText: {
    textAlign: "center",
    fontSize: "13px",
    color: "#888",
    fontFamily: "'Arial', sans-serif",
  },
  signupLink: {
    color: "#4f46e5",
    textDecoration: "none",
    fontWeight: "500",
  },
  successBox: {
    textAlign: "center",
    padding: "1.5rem 0",
  },
  successIcon: {
    fontSize: "48px",
    marginBottom: "12px",
  },
  successTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#111",
    marginBottom: "6px",
  },
  successSub: {
    fontSize: "13px",
    color: "#888",
    fontFamily: "'Arial', sans-serif",
  },
};